######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 14 15:56:59 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
CONFIG   -= app_bundle

# Input
SOURCES += main.cpp \
    newuser.cpp \
    chooseuser.cpp

HEADERS += \
    newuser.h \
    chooseuser.h

FORMS += \
    newuser.ui \
    chooseuser.ui
